export const API_URL = {
  // BASEURL: "http://localhost:8001/",
  BASEURL: "https://expense-server-ynzi.onrender.com/",
  SIGNUP: "signup",
  SIGNIN: "signin",
  EXPENSESLIST: "expenseslist",
  EXPENSES: "expenses",
  CHANGEPASSWORD: "change-password",
  USERS: "users",
  CREATECLIENTUSER: "createclientuser",
  TODOS: "todos",
  TODOLIST: "todolist",
  VERIFYEMAIL: "verifyemail",
  FORGOTPASSWORD: "forgotpassword",
};
